<a href="https://colab.research.google.com/github/leminhquoc248/Machine_Learning_code/blob/main/Machine_learning_chapter_3_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Load library
import pandas as pd
from google.colab import files
uploaded=files.upload()


Saving titanic.csv to titanic.csv


In [ ]:
# Load data as a dataframe
dataframe = pd.read_csv('titanic.csv')
# Show first 5 rows
dataframe.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
# Load thu vien
import pandas as pd
# tao bang dl
dataframe = pd.DataFrame()
# them cot
dataframe['Name'] = ['Jacky Jackson', 'Steven Stevenson']
dataframe['Age'] = [38, 25]
dataframe['Driver'] = [True, False]
# Show Dl
dataframe

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [ ]:
# tao hang
new_person = pd.Series(['Molly Mooney', 40, True], index=['Name','Age','Driver'])
# chen hang
dataframe.append(new_person, ignore_index=True)


Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False
2      Molly Mooney   40    True

In [ ]:
# Load data
dataframe = pd.read_csv('titanic.csv')
# hien thi 2 hang
dataframe.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [ ]:
# Show kich thuoc
dataframe.shape

(891, 12)

In [ ]:
# Show thong ke
dataframe.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
# chon hang dau
dataframe.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
# chon 3 hang
dataframe.iloc[1:4]

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [ ]:
# chon 3 cot
dataframe.iloc[:4]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [ ]:
# set phan tu
dataframe = dataframe.set_index(dataframe['Name'])
# show hang
dataframe.loc['Heikkinen, Miss. Laina']

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                              26.0
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: Heikkinen, Miss. Laina, dtype: object

In [ ]:
# Show 2 nguoi co gioi tinh nu
dataframe[dataframe['Sex'] == 'female'].head(2)

PassengerId  Survived  \
Name                                                                        
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Heikkinen, Miss. Laina                                        3         1   

                                                    Pclass  \
Name                                                         
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1   
Heikkinen, Miss. Laina                                   3   

                                                                                                 Name  \
Name                                                                                                    
Cumings, Mrs. John Bradley (Florence Briggs Tha...  Cumings, Mrs. John Bradley (Florence Briggs Th...   
Heikkinen, Miss. Laina                                                         Heikkinen, Miss. Laina   

                                                       Sex   Age  SibSp  \
Name                                                                      
Cumings, Mrs. John Bradley (Florence Briggs Tha...  female  38.0      1   
Heikkinen, Miss. Laina                              female  26.0      0   

                                                    Parch            Ticket  \
Name                                                                          
Cumings, Mrs. John Bradley (Florence Briggs Tha...      0          PC 17599   
Heikkinen, Miss. Laina                                  0  STON/O2. 3101282   

                                                       Fare Cabin Embarked  
Name                                                                        
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85        C  
Heikkinen, Miss. Laina                               7.9250   NaN        S

In [ ]:
# loc hang
dataframe[(dataframe['Sex'] == 'female') & (dataframe['Age'] >= 65)]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [ ]:
# Replace values, show two rows
dataframe['Sex'].replace("female", "Woman").head(2)

Name
Braund, Mr. Owen Harris                                 male
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    Woman
Name: Sex, dtype: object

In [ ]:
# Replace "female" and "male with "Woman" and "Man"
dataframe['Sex'].replace(["female", "male"], ["Woman", "Man"]).head(5)




Name
Braund, Mr. Owen Harris                                  Man
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    Woman
Heikkinen, Miss. Laina                                 Woman
Futrelle, Mrs. Jacques Heath (Lily May Peel)           Woman
Allen, Mr. William Henry                                 Man
Name: Sex, dtype: object

In [ ]:
# Replace values, show two rows
dataframe.replace(1, "One").head(2)

PassengerId Survived  \
Name                                                                      
Braund, Mr. Owen Harris                                    One        0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...           2      One   

                                                   Pclass  \
Name                                                        
Braund, Mr. Owen Harris                                 3   
Cumings, Mrs. John Bradley (Florence Briggs Tha...    One   

                                                                                                 Name  \
Name                                                                                                    
Braund, Mr. Owen Harris                                                       Braund, Mr. Owen Harris   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  Cumings, Mrs. John Bradley (Florence Briggs Th...   

                                                       Sex   Age SibSp Parch  \
Name                                                                           
Braund, Mr. Owen Harris                               male  22.0   One     0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  female  38.0   One     0   

                                                       Ticket     Fare Cabin  \
Name                                                                           
Braund, Mr. Owen Harris                             A/5 21171   7.2500   NaN   
Cumings, Mrs. John Bradley (Florence Briggs Tha...   PC 17599  71.2833   C85   

                                                   Embarked  
Name                                                         
Braund, Mr. Owen Harris                                   S  
Cumings, Mrs. John Bradley (Florence Briggs Tha...        C

In [ ]:
# Replace values, show two rows
dataframe.replace(r"1st", "First", regex=True).head(2)

PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   

                                                    Pclass  \
Name                                                         
Braund, Mr. Owen Harris                                  3   
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1   

                                                                                                 Name  \
Name                                                                                                    
Braund, Mr. Owen Harris                                                       Braund, Mr. Owen Harris   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  Cumings, Mrs. John Bradley (Florence Briggs Th...   

                                                       Sex   Age  SibSp  \
Name                                                                      
Braund, Mr. Owen Harris                               male  22.0      1   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  female  38.0      1   

                                                    Parch     Ticket     Fare  \
Name                                                                            
Braund, Mr. Owen Harris                                 0  A/5 21171   7.2500   
Cumings, Mrs. John Bradley (Florence Briggs Tha...      0   PC 17599  71.2833   

                                                   Cabin Embarked  
Name                                                               
Braund, Mr. Owen Harris                              NaN        S  
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C

In [ ]:
# Rename column, show two rows
dataframe.rename(columns={'PClass': 'Passenger Class'}).head(2)

PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   

                                                    Pclass  \
Name                                                         
Braund, Mr. Owen Harris                                  3   
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1   

                                                                                                 Name  \
Name                                                                                                    
Braund, Mr. Owen Harris                                                       Braund, Mr. Owen Harris   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  Cumings, Mrs. John Bradley (Florence Briggs Th...   

                                                       Sex   Age  SibSp  \
Name                                                                      
Braund, Mr. Owen Harris                               male  22.0      1   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  female  38.0      1   

                                                    Parch     Ticket     Fare  \
Name                                                                            
Braund, Mr. Owen Harris                                 0  A/5 21171   7.2500   
Cumings, Mrs. John Bradley (Florence Briggs Tha...      0   PC 17599  71.2833   

                                                   Cabin Embarked  
Name                                                               
Braund, Mr. Owen Harris                              NaN        S  
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C

In [ ]:
# Rename columns, show two rows
dataframe.rename(columns={'PClass': 'Passenger Class', 'Sex': 'Gender'}).head(2)

PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   

                                                    Pclass  \
Name                                                         
Braund, Mr. Owen Harris                                  3   
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1   

                                                                                                 Name  \
Name                                                                                                    
Braund, Mr. Owen Harris                                                       Braund, Mr. Owen Harris   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  Cumings, Mrs. John Bradley (Florence Briggs Th...   

                                                    Gender   Age  SibSp  \
Name                                                                      
Braund, Mr. Owen Harris                               male  22.0      1   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  female  38.0      1   

                                                    Parch     Ticket     Fare  \
Name                                                                            
Braund, Mr. Owen Harris                                 0  A/5 21171   7.2500   
Cumings, Mrs. John Bradley (Florence Briggs Tha...      0   PC 17599  71.2833   

                                                   Cabin Embarked  
Name                                                               
Braund, Mr. Owen Harris                              NaN        S  
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C

In [ ]:
# Load library
import collections
# Create dictionary
column_names = collections.defaultdict(str)
# Create keys
for name in dataframe.columns:
    column_names[name]


In [ ]:
# Calculate statistics
print('Maximum:', dataframe['Age'].max())
print('Minimum:', dataframe['Age'].min())
print('Mean:', dataframe['Age'].mean())
print('Sum:', dataframe['Age'].sum())
print('Count:', dataframe['Age'].count())

Maximum: 80.0
Minimum: 0.42
Mean: 29.69911764705882
Sum: 21205.17
Count: 714


In [ ]:
# Show counts
dataframe.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [ ]:
# Select unique values
dataframe['Sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
# Show counts
dataframe['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
## Select missing values, show two rows
dataframe[dataframe['Age'].isnull()].head(2)

PassengerId  Survived  Pclass  \
Name                                                          
Moran, Mr. James                        6         0       3   
Williams, Mr. Charles Eugene           18         1       2   

                                                      Name   Sex  Age  SibSp  \
Name                                                                           
Moran, Mr. James                          Moran, Mr. James  male  NaN      0   
Williams, Mr. Charles Eugene  Williams, Mr. Charles Eugene  male  NaN      0   

                              Parch  Ticket     Fare Cabin Embarked  
Name                                                                 
Moran, Mr. James                  0  330877   8.4583   NaN        Q  
Williams, Mr. Charles Eugene      0  244373  13.0000   NaN        S

In [ ]:
dataframe = pd.read_csv('titanic.csv')

In [ ]:
# Delete column
dataframe.drop('Age', axis=1).head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   

      Ticket     Fare Cabin Embarked  
0  A/5 21171   7.2500   NaN        S  
1   PC 17599  71.2833   C85        C

In [ ]:
# Drop columns
dataframe.drop(['Age', 'Sex'], axis=1).head(2)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name  SibSp  Parch     Ticket  \
0                            Braund, Mr. Owen Harris      1      0  A/5 21171   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      1      0   PC 17599   

      Fare Cabin Embarked  
0   7.2500   NaN        S  
1  71.2833   C85        C

In [ ]:
# Drop column
dataframe.drop(dataframe.columns[1], axis=1).head(2)

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   

      Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
0    male  22.0      1      0  A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0   PC 17599  71.2833   C85        C

In [ ]:
# Create a new DataFrame
dataframe_name_dropped = dataframe.drop(dataframe.columns[0], axis=1)

In [ ]:
# Delete row, show first two rows of output
dataframe[dataframe['Name'] != 'Allison, Miss Helen Loraine'].head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [ ]:
# Delete row, show first two rows of output
dataframe[dataframe.index != 0].head(2)

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [ ]:
# Drop duplicates, show first two rows of output
dataframe.drop_duplicates().head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [ ]:
# Show number of rows
print("Number Of Rows In The Original DataFrame:", len(dataframe))
print("Number Of Rows After Deduping:", len(dataframe.drop_duplicates()))

Number Of Rows In The Original DataFrame: 891
Number Of Rows After Deduping: 891


In [ ]:
# Drop duplicates
dataframe.drop_duplicates(subset=['Sex'])

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [ ]:
# Drop duplicates
dataframe.drop_duplicates(subset=['Sex'], keep='last')

PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [ ]:
dataframe.groupby('Sex').mean()


PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Sex                                                                      
female   431.028662  0.742038  2.159236  27.915709  0.694268  0.649682   
male     454.147314  0.188908  2.389948  30.726645  0.429809  0.235702   

             Fare  
Sex                
female  44.479818  
male    25.523893

In [ ]:
dataframe.groupby('Sex')

In [ ]:
dataframe.groupby('Survived')['Name'].count()

Survived
0    549
1    342
Name: Name, dtype: int64

In [ ]:
dataframe.groupby(['Sex','Survived'])['Age'].mean()

Sex     Survived
female  0           25.046875
        1           28.847716
male    0           31.618056
        1           27.276022
Name: Age, dtype: float64

In [ ]:
# Load libraries
import pandas as pd
import numpy as np
# Create date range
time_index = pd.date_range('06/06/2017', periods=100000, freq='30S')
# Create DataFrame
dataframe = pd.DataFrame(index=time_index)
# Create column of random values
dataframe['Sale_Amount'] = np.random.randint(1, 10, 100000)

In [ ]:
# Group rows by week, calculate sum per week
dataframe.resample('W').sum()

Sale_Amount
2017-06-11        85775
2017-06-18       100387
2017-06-25       100262
2017-07-02       100549
2017-07-09       100789
2017-07-16        10284

In [ ]:
# Show three rows
dataframe.head(3)

Sale_Amount
2017-06-06 00:00:00            7
2017-06-06 00:00:30            9
2017-06-06 00:01:00            6

In [ ]:
# Group by two weeks, calculate mean
dataframe.resample('2W').mean()

Sale_Amount
2017-06-11     4.963831
2017-06-25     4.976414
2017-07-09     4.993502
2017-07-23     4.944231

In [ ]:
# Group by month, count rows
dataframe.resample('M').count()

Sale_Amount
2017-06-30        72000
2017-07-31        28000

In [ ]:
# Group by month, count rows
dataframe.resample('M', label='left').count()

Sale_Amount
2017-05-31        72000
2017-06-30        28000

In [ ]:
data_a = {'id': ['1', '2', '3'],
'first': ['Alex', 'Amy', 'Allen'],
'last': ['Anderson', 'Ackerman', 'Ali']}
dataframe_a = pd.DataFrame(data_a, columns = ['id', 'first', 'last'])
# Create DataFrame
data_b = {'id': ['4', '5', '6'],
'first': ['Billy', 'Brian', 'Bran'],
'last': ['Bonder', 'Black', 'Balwner']}
dataframe_b = pd.DataFrame(data_b, columns = ['id', 'first', 'last'])
# Concatenate DataFrames by rows
pd.concat([dataframe_a, dataframe_b], axis=0)

id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali
0  4  Billy    Bonder
1  5  Brian     Black
2  6   Bran   Balwner

In [ ]:
# Concatenate DataFrames by columns
pd.concat([dataframe_a, dataframe_b], axis=1)

id  first      last id  first     last
0  1   Alex  Anderson  4  Billy   Bonder
1  2    Amy  Ackerman  5  Brian    Black
2  3  Allen       Ali  6   Bran  Balwner

In [ ]:
# Create row
row = pd.Series([10, 'Chris', 'Chillon'], index=['id', 'first', 'last'])
# Append row
dataframe_a.append(row, ignore_index=True)

id  first      last
0   1   Alex  Anderson
1   2    Amy  Ackerman
2   3  Allen       Ali
3  10  Chris   Chillon

In [ ]:
# Load library
import pandas as pd
# Create DataFrame
employee_data = {'employee_id': ['1', '2', '3', '4'],
'name': ['Amy Jones', 'Allen Keys', 'Alice Bees',
'Tim Horton']}
dataframe_employees = pd.DataFrame(employee_data, columns = ['employee_id',
'name'])
# Create DataFrame
sales_data = {'employee_id': ['3', '4', '5', '6'],
'total_sales': [23456, 2512, 2345, 1455]}
dataframe_sales = pd.DataFrame(sales_data, columns = ['employee_id',
'total_sales'])
# Merge DataFrames
pd.merge(dataframe_employees, dataframe_sales, on='employee_id')


employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512

In [ ]:
# Merge DataFrames
pd.merge(dataframe_employees, dataframe_sales, on='employee_id', how='outer')

employee_id        name  total_sales
0           1   Amy Jones          NaN
1           2  Allen Keys          NaN
2           3  Alice Bees      23456.0
3           4  Tim Horton       2512.0
4           5         NaN       2345.0
5           6         NaN       1455.0

In [ ]:
# Merge DataFrames
pd.merge(dataframe_employees, dataframe_sales, on='employee_id', how='left')

employee_id        name  total_sales
0           1   Amy Jones          NaN
1           2  Allen Keys          NaN
2           3  Alice Bees      23456.0
3           4  Tim Horton       2512.0

In [ ]:
# Merge DataFrames
pd.merge(dataframe_employees,
dataframe_sales,
left_on='employee_id',
right_on='employee_id')

employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512

chapter 4

In [ ]:
# Load libraries
import numpy as np
from sklearn import preprocessing
# Create feature
feature = np.array([[-500.5],
[-100.1],
[0],
[100.1],
[900.9]])
# Create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

In [ ]:
# Scale feature
scaled_feature = minmax_scale.fit_transform(feature)
# Show feature
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [ ]:
# Create feature
x = np.array([[-1000.1],
[-200.2],
[500.5],
[600.6],
[9000.9]])
# Create scaler
scaler = preprocessing.StandardScaler()
# Transform the feature
standardized = scaler.fit_transform(x)
# Show feature
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [ ]:
# Print mean and standard deviation
print("Mean:", round(standardized.mean()))
print("Standard deviation:", standardized.std())

Mean: 0
Standard deviation: 1.0


In [ ]:
# Create scaler
robust_scaler = preprocessing.RobustScaler()
# Transform feature
robust_scaler.fit_transform(x)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

In [ ]:
# Load libraries
import numpy as np
from sklearn.preprocessing import Normalizer
# Create feature matrix
features = np.array([[0.5, 0.5],
[1.1, 3.4],
[1.5, 20.2],
[1.63, 34.4],
[10.9, 3.3]])
# Create normalizer
normalizer = Normalizer(norm="l2")
# Transform feature matrix
normalizer.transform(features)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [ ]:
# Transform feature matrix
features_l2_norm = Normalizer(norm="l2").transform(features)
# Show feature matrix
features_l2_norm

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [ ]:
# Transform feature matrix
features_l1_norm = Normalizer(norm="l1").transform(features)
# Show feature matrix
features_l1_norm

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [ ]:
# Print sum
print("Sum of the first observation\'s values:",
features_l1_norm[0, 0] + features_l1_norm[0, 1])

Sum of the first observation's values: 1.0


In [ ]:
# Load libraries
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
# Create feature matrix
features = np.array([[2, 3],
[2, 3],
[2, 3]])

In [ ]:
# Create PolynomialFeatures object
polynomial_interaction = PolynomialFeatures(degree=2, include_bias=False)
# Create polynomial features
polynomial_interaction.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

In [ ]:
interaction = PolynomialFeatures(degree=2,
interaction_only=True, include_bias=False)
interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

In [ ]:
# Load libraries
import numpy as np
from sklearn.preprocessing import FunctionTransformer
# Create feature matrix
features = np.array([[2, 3],
[2, 3],
[2, 3]])
# Define a simple function
def add_ten(x):
 return x + 10
# Create transformer
ten_transformer = FunctionTransformer(add_ten)
# Transform feature matrix
ten_transformer.transform(features)

array([[12, 13],
       [12, 13],
       [12, 13]])

In [ ]:
# Load library
import pandas as pd
# Create DataFrame
df = pd.DataFrame(features, columns=["feature_1", "feature_2"])

In [ ]:
# Apply function
df.apply(add_ten)

feature_1  feature_2
0         12         13
1         12         13
2         12         13

In [ ]:
# Load libraries
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs
# Create simulated data
features, _ = make_blobs(n_samples = 10,
n_features = 2,
centers = 1,
random_state = 1)
# Replace the first observation's values with extreme values
features[0,0] = 10000
features[0,1] = 10000

In [ ]:
outlier_detector = EllipticEnvelope(contamination=.1)
# Fit detector
outlier_detector.fit(features)
# Predict outliers
outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [ ]:
# Create one feature
feature = features[:,0]
# Create a function to return index of outliers
def indicies_of_outliers(x):
 q1, q3 = np.percentile(x, [25, 75])
 iqr = q3 - q1
 lower_bound = q1 - (iqr * 1.5)
 upper_bound = q3 + (iqr * 1.5)
 return np.where((x > upper_bound) | (x < lower_bound))
# Run function
indicies_of_outliers(feature)

(array([0]),)

In [ ]:
# Load library
import pandas as pd
# Create DataFrame
houses = pd.DataFrame()
houses['Price'] = [534433, 392333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]
# Filter observations
houses[houses['Bathrooms'] < 20]

Price  Bathrooms  Square_Feet
0  534433        2.0         1500
1  392333        3.5         2500
2  293222        2.0         1500

In [ ]:
# Create feature based on boolean condition
houses["Outlier"] = np.where(houses["Bathrooms"] < 20, 0, 1)
# Show data
houses

Price  Bathrooms  Square_Feet  Outlier
0   534433        2.0         1500        0
1   392333        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        48000        1

In [ ]:
# Log feature
houses["Log_Of_Square_Feet"] = [np.log(x) for x in houses["Square_Feet"]]
# Show data
houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956

In [ ]:
# Load libraries
import numpy as np
from sklearn.preprocessing import Binarizer
# Create feature
age = np.array([[6],
[12],
[20],
[36],
[65]])


In [ ]:
# Bin feature
np.digitize(age, bins=[20,30,64])


array([[0],
       [0],
       [1],
       [2],
       [3]])

In [ ]:
# Bin feature
np.digitize(age, bins=[20,30,64], right=True)

array([[0],
       [0],
       [0],
       [2],
       [3]])

In [ ]:
# Bin feature
np.digitize(age, bins=[18])

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [ ]:
# Load libraries
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
# Make simulated feature matrix
features, _ = make_blobs(n_samples = 50,
n_features = 2,
centers = 3,
random_state = 1)
# Create DataFrame
dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])
# Make k-means clusterer
clusterer = KMeans(3, random_state=0)
# Fit clusterer
clusterer.fit(features)
# Predict values
dataframe["group"] = clusterer.predict(features)
# View first few observations
dataframe.head(5)

feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2

In [ ]:
# Load library
import numpy as np
# Create feature matrix
features = np.array([[1.1, 11.1],
[2.2, 22.2],
[3.3, 33.3],
[4.4, 44.4],
[np.nan, 55]])
# Keep only observations that are not (denoted by ~) missing
features[~np.isnan(features).any(axis=1)]

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4]])

In [ ]:

import pandas as pd
# Load data
dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])
# Remove observations with missing values
dataframe.dropna()

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4